<a href="https://colab.research.google.com/github/fayzullaevfarrukh98/ai_foundation/blob/master/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install numpy


In [ ]:
import numpy as np

arr = np.array([1, 3, 5, 7])
print('numpy_array:', arr)

arr.shape

numpy_array: [1 3 5 7]


(4,)

In [ ]:
arr2 = np.array([[1, 3, 5, 7], [2, 4, 6, 8]])
print('numpy_array2:', arr2)

arr2.shape

numpy_array2: [[1 3 5 7]
 [2 4 6 8]]


(2, 4)

In [ ]:
# dtype()
a = np.array([1, 2, 3])
print(a.dtype)

int64


In [5]:
import numpy as np
# reshape()
a = np.array([1, 2, 3, 4, 5, 6])
b = a.reshape(2, 3)
print("shaped_array:", b)

shaped_array: [[1 2 3]
 [4 5 6]]


In [2]:
import numpy as np
# astype()
a = np.array([1, 2, 3])
b = a.astype(float)
print("float:", b)

float: [1. 2. 3.]


In [3]:
# np.zeros(), mp.ones() => dummy data
z = np.zeros((2, 3))
o = np.ones((2, 3))

print("zeros:", z)
print("ones:", o)

zeros: [[0. 0. 0.]
 [0. 0. 0.]]
ones: [[1. 1. 1.]
 [1. 1. 1.]]


In [5]:
# ndim
a = np.array([[1, 2.], [3, 4]])
print("ndim:", a.ndim)

ndim: 2


In [6]:
# arange()
a = np.arange(1, 7)
print("arange:", a)

arange: [1 2 3 4 5 6]


In [7]:
# sum(), mean(), max(), min()

a = np.array([1, 2, 3, 4])
print("sum:", a.sum())
print("mean:", a.mean())
print("max:", a.max())
print("min:", a.min())

sum: 10
mean: 2.5
max: 4
min: 1


In [30]:
# flatten()

a = np.array([[1, 2], [3, 4]])
print("flatten:", a.flatten())

flatten: [1 2 3 4]


In [31]:
# T(Transpose)
a = np.array([[1, 2], [3, 4]])
print("transpose:", a.T)

transpose: [[1 3]
 [2 4]]


In [46]:
# dot() @
a = np.array([[1, 2], [3, 4]])
b = np.array([[2, 0], [1, 2]])
print("dot/multiplication:", a.dot(b))

dot/multiplication: [[ 4  4]
 [10  8]]


In [67]:
# random.rand()
a = np.random.rand(2, 3)
print("random:", a)


random: [[0.41966367 0.89145497 0.66433886]
 [0.05464683 0.60640219 0.00359837]]
